title: How Photograph
author: Hao
email: haofu9003@gmail.com
description: |
  Welcome to How Photograph! <br>
  My name is Hao, it sounds like 'how'. And I'm passionate about capturing the perfect shot and constantly exploring ways to improve my photography skills.  <br>
  That's why I named my photo website 'How Photograph', a place where I share my journey. <br>


#social:
#twitter: joaomlneto
#facebook: joaomlneto
#instagram: joaomlneto
#github: joaomlneto
#linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
