title: Hao's Photograph
author: Hao Fu
email: haofu@utexas.edu
description: >-
  show my pictures

#social:
 # twitter: joaomlneto
  #facebook: joaomlneto
  #instagram: joaomlneto
  #github: joaomlneto
  #linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
