title: How Photograph
author: Hao
email: haofu9003@gmail.com
description: |
  Welcome to How Photograph! <br>
  My name is Hao, it sounds like 'how'. And I'm constantly exploring how to improve my photography skills.<br>
  That's why I named my photo website 'How Photograph'.<br>
  If you have any questions or comments, please contact me via the email. <br>
  Commercial use is prohibited without permission.


#social:
#twitter: joaomlneto
#facebook: joaomlneto
#instagram: joaomlneto
#github: joaomlneto
#linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
